lesson 11
BystrovN/test_guru pull request #10
Opened 2024-02-15 22:14 UTC by BystrovN

2024-02-16 06:52 UTC, VidgarVii requested changes

2024-02-16 06:52 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  def start
экшен `start` в контроллере админа не нужен
это функционал пользователя

2024-02-16 06:52 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @test.author = current_user
авторство правильней (более "рельсово") задавать через ассоциации
смотри https://github.com/BystrovN/test_guru/pull/10/files#diff-8c6583b897d2be3e5daa549b7e9764f5d509e700dfa19a289d11446a5fa483fdR14

2024-02-16 06:52 UTC, VidgarVii commented on app/controllers/application_controller.rb
>    end
этот метод должен просто возвращать путь
то что он еще и флеш устанавливает - неожиданный сайд эффект
к примеру, есть задача:
в админке выводить список пользователей с урлами, куда каждый будет редиректнут после логина
метод называется `after_sign_in_path_for(user)` - вполне логично им воспользоваться
и вдруг неожиданность - у админа почему-то выводится флеш-привествие )))
ТЗ: "... после входа, выводить флэш-сообщение ..."
обрати внимание - "после входа", т.е. установку флеша надо делать там, где происходит логин пользователя (создание сессии), т.е. в `SessionsController`

2024-02-16 06:52 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: [:start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2024-02-16 06:52 UTC, VidgarVii commented on app/controllers/users/registrations_controller.rb
> +    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
для добавления параметров есть хелпер 
configure_permitted_parameters
https://github.com/heartcombo/devise?tab=readme-ov-file#strong-parameters

2024-02-16 20:56 UTC, BystrovN commented on app/controllers/application_controller.rb
>    end
👍

2024-02-17 06:14 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  before_action :find_test, only: %i[show edit update destroy start]
из колбкеа тоже надо удалить экшен start

2024-02-17 10:22 UTC, merged