lesson_14
BystrovN/test_guru pull request #13
Opened 2024-02-22 21:23 UTC by BystrovN

2024-02-23 10:03 UTC, VidgarVii requested changes

2024-02-23 10:03 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails', '~> 3.0'
данный гем должен использоваться только в дев и тест окружении

2024-02-23 10:03 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
Повод вспомнить про REST.
Gist это ресурс. Значит согласно rails way и REST для создания ресурса и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2024-02-23 10:03 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    if gist_url.present?
Суть создания отдельного класса - вынести в него часть логики и скрыть детали реализации. Логика определения успешности создания Гиста тоже лучше оставить в сервис и не мучить дополнительной сложностью контроллер. 
Но проверять успех в контроллере конечно надо.
Для этого есть стандартный подход для контроллера при работе с любым сервисом

```ruby
result = SomeService.new(...).call

if result.success?
  ...
else
  ...
end
```
 Метод call должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct 
Минус твоего подхода в том, что если придётся менять гем, то придётся исправлять код в разных местах проекта. А класс GistQuestionService служит своего рода адаптером над октокит. Его задача не только создавать гист. Это он вообще делегирует гему октокит. А скрыть сложность создания гиста и предоставить общий интерфейс, который не зависит от хттп клиента. И если придётся менять этот хттп клиент, то рефакторигну подвергнется только сервис  GistQuestionService

2024-02-23 10:03 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      flash_options = { notice: t('.success', url: gist_url) }
ссылка должна быть кликабельной

2024-02-23 10:03 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2024-02-23 10:03 UTC, VidgarVii commented on db/migrate/20240222171137_create_gists.rb
> +      t.references :user, foreign_key: true
не забываем про null false

2024-02-23 21:50 UTC, BystrovN commented on app/controllers/test_passages_controller.rb
> +    if gist_url.present?
👍

2024-02-24 12:46 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :find_test_passage, only: %i[show update result gist]
надо убрать лишний экшен

2024-02-24 13:20 UTC, merged