lesson_18 part 1
BystrovN/test_guru pull request #17
Opened 2024-03-05 21:46 UTC by BystrovN

2024-03-06 04:57 UTC, VidgarVii requested changes

2024-03-06 04:57 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    @badge.badge_rules << @rule
каждый раз будет одно и тоже правило добавляться?

2024-03-06 04:57 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    @rule = BadgeRule.find(params[:badge][:badge_rule_id])
как админ будет выбирать опцию для правила?

2024-03-06 04:57 UTC, VidgarVii commented on app/models/badge_rule.rb
> +end
для статичных данных модель не нужна и таблица не нужна. Константу можно объявить в классе Badge

2024-03-06 04:57 UTC, VidgarVii commented on db/migrate/20240304182025_create_badge_rules.rb
> +      t.integer :type_, null: false
не корректное название для поля. Подчеркивание выглядит как костыль. Стоит придумать более точное название

2024-03-06 04:57 UTC, VidgarVii commented on app/models/concerns/rule_types.rb
> +module RuleTypes
не точное использование консернов. Лишняя сложность.
Будет по ним еще урок.

2024-03-06 04:57 UTC, VidgarVii commented on app/services/badge_service.rb
> +    BadgeRule.all.each do |rule|
лучше используй find_each для итераций.
метод .all почти не используют. Так как если в БД окажется большое кол-во данных, то данный метод полностью заполнит оперативную память.  И сервер зависнет

2024-03-06 04:57 UTC, VidgarVii commented on app/services/badge_service.rb
> +  end
по названиям методов можно понять что они должны совершать проверки. А в итоге везде имеется грубый сайд эффек добавляение баджда юзеру. Надо разделять логику действий.
На много лучше будет, сначала найти все нужные баджи, а потом 1 раз их добавить юзеру

2024-03-06 04:57 UTC, VidgarVii commented on app/services/badge_service.rb
> +end
в проверках везде используется уникальность. Получается что юзер после получения 1 баджа. Будет и далее его получать если он пройден 1 тест еще раз. Да по ТЗ
**Пользователь может получать один и тот же бэйдж более одного раза**
Но не каждый ведь раз, после прохождения 1 теста например определенного уровня. Надо пройти еще раз ВСЕ тесты данного уровня или категории. Этой проверки я не увидел

2024-03-06 04:57 UTC, VidgarVii commented on app/services/badge_service.rb
> +end
не указан модификатор доступа

2024-03-06 07:55 UTC, BystrovN commented on app/models/badge_rule.rb
> +end
Почему правило это статичные данные, если условие и тип указываются при создании записи в бд? Вон ниже даже замечание к этой же миграции имеется

2024-03-06 15:58 UTC, BystrovN commented on app/controllers/admin/badges_controller.rb
> +    @rule = BadgeRule.find(params[:badge][:badge_rule_id])
Никак, админ выбирает только правило. 
<img width="627" alt="Снимок экрана 2024-03-06 в 18 30 04" src="https://github.com/BystrovN/test_guru/assets/105677259/557b3d5a-54a1-4743-ba54-caa56687740b">

Поскольку в ТЗ есть пункт: "Допускается что критерии правил заданы заранее, например на уровне атрибутов модели" посчитал подобный вариант допустимым

2024-03-07 06:48 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    @rule = BadgeRule.find(params[:badge][:badge_rule_id])
тут нет выбора самой категории или уровня теста

2024-03-07 06:50 UTC, VidgarVii commented on app/models/badge_rule.rb
> +end
типы указаны в константе. Для этого модель не нужна. Достаточно enam в моделе Badge

2024-03-07 06:52 UTC, VidgarVii commented on app/services/badge_service.rb
> +end
Еще стоит подумать на масштабируемостью. Что тут будет если типов правил будет больше. Данный класс очень быстро разбухнет

2024-03-08 09:07 UTC, VidgarVii requested changes

2024-03-08 09:07 UTC, VidgarVii commented on app/models/badge_rule.rb
> +                         "Пройти все тесты категории #{Category.find(condition).title}"
Мы уже проходили тему локализаци. Весь контекст надо хранить там.

2024-03-08 09:07 UTC, VidgarVii commented on app/models/badge_rule.rb
> +  module RuleTypes
модули внутри классов не объявляют. Надо подтягивать понимание ООП. Это тоже самое что внутрь человека засунуть сумку с инструментами, чтобы сделать из него, например электрика. Технически вроде возможно, но....

2024-03-08 09:07 UTC, VidgarVii commented on app/models/badge_rule.rb
> +
вспоминаем соглашение создание моделей в rails style guide и наводим порядок.

2024-03-08 09:07 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +  end
как то всё сложно. Я не совсем понимаю зачем нужен BadgeRule. Что он нам даёт?
Действительно возможно реализация через 2 модели. Но тут надо понимать желание разработчика и возможности кода. Сейчас у меня такого понимания нет. Попробуй объяснить. И по ТЗ достаточно одной модели

2024-03-08 09:07 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    @rule = BadgeRule.find_or_create_by(
find_rule подразумевает поиск объекта, а не создание. Это очень грубый сайд еффект

2024-03-08 09:07 UTC, VidgarVii commented on app/services/badge_service.rb
> +end
проблема раздутия класса не решилось

2024-03-08 09:23 UTC, BystrovN commented on app/controllers/admin/badges_controller.rb
> +  end
Отдельная модель для правила так как мы представляем объекты реального мира в нашем коде. Бейдж не содержит в себе правил получения себя. Правило описано в объекта, относящимся к ним. Поэтому я разделил это в разные сущности. Хорошо, если мой подход приводит к замечаниям, которые катаются по одному и тому же, то ок, я вынесу правила в сущность бейжда, желания это продолжать обсуждать не вижу смысла

2024-03-11 05:05 UTC, VidgarVii commented on Gemfile
> +  gem 'sqlite3'
зачем нужен sqlite3, если выше уже подключен постгрес?

2024-03-11 17:16 UTC, merged